### ISSUE TITLE
Zabbix 3.4 agent timeout no data in Zabbix

### ISSUE THREAD

**Issue by jesse-thomas** [jamestutton/ESP8266-Based-Hardware-Zabbix-Agent#1]
https://github.com/jamestutton/ESP8266-Based-Hardware-Zabbix-Agent/blob/8f99a28a8544b4e073846f4d5293371cfef557ab/ESP8266_Zabbix_Passive_Agent_with_Motion.ino#L267

I changed 
String cmd = client.readStringUntil('\r');
to 
String cmd = client.readStringUntil('\n');

and it worked!

using \r the esp8266 took about a second to respond, it responded instantly with \n

**Comment by jamestutton** [comment]
Thanks for the feedback suggestion implemented
